### ISSUE TITLE
Idea: Singleton streams(??)

### ISSUE THREAD

**Issue by mikabytes** [tidenjs/tiden#14]
As is often the case, many streams and nanos depend on the same stream. Earlier we've resolved the issue of starting a stream by placing it in the apps startup scripts. This works, but it has some drawbacks:

- Unused streams will still run
- Streams have to be started by nano tests. This is tedious and error-prone, as often a stream has its own dependencies (which are prone to change)

This idea mitigates these issues by:

- A stream may be started by any other stream, nano, or other
- Multiple instances of a stream is already forbidden, so if it is already running it should be safe to ignore starting a stream that has already been started

IF this gets implemented, then we'd have the following **pros**:

- A stream/nano declares what other streams it depends on (increased readability, understanding of the system)
- Tests don't need to explicitly startup dependencies before running nano
- Exporting a nano becomes trivial. The importing app only needs a reference to the nano. It will fire up depending streams (and their depending streams) automatically.

However, we also get the following **cons**:

- Every stream now has a hard dependency rather than a soft one. In situations where the Tiden app is split in several repositories then a stream cannot be used cross-repo. This might be a showstopper. Need more investigation.

**or, alternate idea:**

A stream is never started when it is run. Instead, it merely register its existence to Tiden. When Tiden sees any request made to the stream name, then it starts it up.

**Comment by mikabytes** [comment]
**mainline idea** example:

stream1 depends on stream2

```
export default function* stream1() {
  const stream2 = yield import(`./stream2.js`)
  yield fork(stream2)
  yield fork(stream2)
  yield fork(stream2)
}
```

Only one instance of stream2 is actually started here, as Tiden keeps track of how many tasks based on that stream has already been started (max 1)

**Comment by jl311888** [comment]
Would circular dependencies be a potential problem?  (stream1 depends on stream2 but stream2 also depends on stream1)

**Comment by mikabytes** [comment]
Oh, I think that could be a problem indeed. But not only with this idea, but in general.

For example, we had this situation `->` means "depends on":

`users` -> `config` -> `hosts` -> `config`

Config needed hosts to fetch its config, but hosts also needed config to figure out where hosts should be fetched from.

Circular dependencies usually point out a design flaw and should be avoided. In this case, before my fix, we'd end up in a feedback loop where hosts and configs were fetched in an endless loop. Not good.

The solution in that case was to hardcode the initial host. 

Tiden should probably disallow such a situation in a similar manner as Chrome does with infinite redirects.

**Comment by mikabytes** [comment]
The more I think of streams-as-dependencies the more I start to think it might be appropriate to have some sort of registry of streams. We probably don't want to make hard dependencies in the scope of nano or a stream because we might not have that information at the time of writing the code. (it would break the use of them as sinks).

At the same time, for the purpose of testing nanos it is often desirable to mock streams. If all streams are always available, but there's a mechanism to replace one or more at will, then the problem is solved. I imagine, it would also improve app startup time when no stream is started until a request is made.

**Comment by mikabytes** [comment]
Also, with a registry, Tiden could be responsible for keeping the stream alive. If it crashes, then log the error and start it up again.

**Comment by mikabytes** [comment]
It has been decided that we will have *named streams*. These can be replaced, or shut down, in a future release. For *Stone*, we will only provide the requirement to name them.

We probably will not implement a means to put them in a "waiting" state before any request is done to it, however, this is the default behavior of `merge` which is also the most used method. So the issue kind of resolves itself.
