### ISSUE TITLE
CLI to assume namespace from cwd

### ISSUE THREAD

**Issue by mikabytes** [tidenjs/tiden#19]
**Is your feature request related to a problem? Please describe.**
Currently, all CLI commands need to be performed in the root of the project. This is not intuitive when working in bigger projects and all releveant work is in a subfolder (that is, a sub namespace).

**Describe the solution you'd like**

_when I'm in `/` or `/app`_: Assume root
_when I'm in `/app/someNamespace`_: Assume someNamespace

**Describe alternatives you've considered**
None.

**Comment by mikabytes** [comment]
It's like this:

```
mkdir myProject
cd myProject
tiden init myProject
```

Now, if I run this command then a component would be created in namespace "documentation" (which is also a folder)

```
tiden create component header namespace
```

This creates a few files, for example `/app/documentation/components/header.js`

This Issue is about assuming namespace from the folder that I've `cd`ed into. So, I'd like to be able to do the same thing as above, but instead by doing this:

```
mkdir myProject
cd myProject
tiden init myProject
cd app/documentation
tiden create component header
```

So, as you see, the namespace was assumed because I had `cd`ed into the folder that represents the namespace.

**Comment by Seke1412** [comment]
https://github.com/tidenjs/tiden/pull/33

**Comment by mikabytes** [comment]
@Seke1412 I make clarifications here rather than in that closed pull request. I like to use issues for specification, and pull-requests for the feedback :) Please give me your feedback on this proposal for strategy.

Strategy proposal regarding "CLI to assume namespace", or better named "CLI to translate namespace using CWD". This strategy encompasses the use of CLI, however, OPS will also need to be respected as it is planned to be used directly by the full IDE (defined in #12).

There will be three modules responsible for managing the logic from command-line to end result:
1. CLI Parser
2. CLI Translator
3. OPS

## CLI parser

INPUT: command-line arguments (an array of strings)         ARGV
OUTPUT: target function and a resulting parsed object       PARSED
UNIT TESTS: **obligatory**

No changes should be necessary to this module for this feature.

## CLI translator

INPUT: PARSED and a directory. The directory should default to CWD (current working directory), however it should be possible to provide any directory.
OUTPUT: PARSED (same as CLI parser), only the object has been modified with respect to the directory.  
UNIT TESTS: **obligatory**

This module doesn't exist, so it will need to be created.

## OPS

INPUT: PARSED
OUTPUT: none.
SIDE-EFFECTS: file-system will be changed, files and directories may be created/deleted/modified
UNIT TESTS: **obligatory**

No changes should be necessary to this module for this feature.

# Example workflow 1: Root folder

```bash
cd . # (we are in the root folder)
tiden create component lizards
```

```
CLI_ARGS = ['tiden', 'create', 'component', 'lizards']
CWD = '.'

PARSED = CLI parser (CLI_ARGS) ---> [func createComponent, { path: undefined, name: 'lizards' }]

PARSED = CLI translator (PARSED, CWD) ---> [func createComponent, { path: ``, name: 'lizards' }]

OPS(PARSED) 
```

# Example workflow 2: In a bad directory

```bash
cd lib
tiden create component lizards
```

```
CLI_ARGS = ['tiden', 'create', 'component', 'lizards']
CWD = './lib'

PARSED = CLI parser (CLI_ARGS) ---> [func createComponent, { path: undefined, name: 'lizards' }]

PARSED = CLI translator (PARSED, CWD) ---> ERROR! Cannot translate into 'lib' folder'

kill process
```

# Example workflow 3: In "app" folder

```bash
cd app
tiden create component lizards
```

```
CLI_ARGS = ['tiden', 'create', 'component', 'lizards']
CWD = './app'

PARSED = CLI parser (CLI_ARGS) ---> [func createComponent, { path: undefined, name: 'lizards' }]

PARSED = CLI translator (PARSED, CWD) ---> [func createComponent, { path: ``, name: 'lizards' }]

OPS(PARSED) 
```


# Example workflow 4: In a namespace folder

```bash
cd app/east/asia # (we are in the east/asia namespace)
tiden create component lizards
```

```
CLI_ARGS = ['tiden', 'create', 'component', 'lizards']
CWD = './app'

PARSED = CLI parser (CLI_ARGS) ---> [func createComponent, { path: undefined, name: 'lizards' }]

PARSED = CLI translator (PARSED, CWD) ---> [func createComponent, { path: `east/asia`, name: 'lizards' }]

OPS(PARSED) # make the desirable side-effects
```

**Comment by Seke1412** [comment]
@mikabytes 

> (cd ./lib && tiden create component lizards)
> 
> CLI_ARGS = ['tiden', 'create', 'component', 'lizards']
> CWD = './lib'
> 
> PARSED = CLI parser (CLI_ARGS) ---> [func createComponent, { path: undefined, name: 'lizards' }]
> 
> CLI translator (PARSED, CWD) ---> ERROR! Cannot translate using 'lib' folder'
> 
> kill process
> 

I want to make this case a little more make sense, let says i'm coding so many tiden project in my machine, each project i put them inside Document/tiden-project and organize them with project1, project2, project3, so there is the case 
```
(cd ./Document/tiden-project/project1 && tiden create component lizards)

CLI_ARGS = ['tiden', 'create', 'component', 'lizards']
CWD = '~/Document/tiden-project/project1' (at this point ~/Document/tiden-project/project1 should be treated as root folder) 
PARSED = CLI parser (CLI_ARGS) ---> [func createComponent, { path: undefined, name: 'lizards' }]

PARSED, ROOT = CLI translator (PARSED, CWD) ---> [func createComponent, { path: ``, name: 'lizards' }]
```

It's also related to a more general cases:

```
(cd ./xxx/app/yyy/app/zzzz/app && tiden create component lizards)

CLI_ARGS = ['tiden', 'create', 'component', 'lizards']
CWD = './xxx/app/yyy/app/zzzz/app' (at this point first app dir should be treated as root folder - ./xxx/app)

PARSED = CLI parser (CLI_ARGS) ---> [func createComponent, { path: undefined, name: 'lizards' }]

PARSED, ROOT = CLI translator (PARSED, CWD) ---> [func createComponent, { path: ``, name: 'lizards' }]

OPS(PARSED)  ----> ./xxx/app/components/lizards/*.js
```

We miss those 2 cases, so just my suggestion to make the create command more consistent and predictable, how do you feel?

**Comment by mikabytes** [comment]
> We miss those 2 cases, so just my suggestion to make the create command more consistent and predictable

I'm struggling to understand the two issues/cases here. So please let me know if I misunderstood something. This is what I think you're asking:

# Issue 1: What do we do when a tiden project is created nested within another tiden project?

I'm not sure if this makes sense. But if it does (and it may), then *the closest project is always the root*. This is similar to how NPM, GIT, RubyGems, and many other CLI tools.

So:

`./xxx/root1/......../root2/zzzz/root3` ---> root is `./xxx/root1/......../root2/zzzz/root3`
`./xxx/root1/......../root2/zzzz/root3/app/east/asia` ---> root is `./xxx/root1/......../root2/zzzz/root3` and namespace is `east/asia`
`./xxx/root1/app/zzzz` ---> root is `./xxx/root1` and namespace is `zzzz`

# Issue 2: How do we know that a folder is a root folder?

I just realized this question hasn't been answered anywhere yet. 

**It is the closest parent that contains a `manifest.json` file.**

It doesn't matter if it contains an `app` folder or not. That would create problems further ahead. Consider for example the path `./lib/app/helpers.js`. The root folder is definitely not `./lib`. Only the `manifest.json` file can identify a root folder.
