### ISSUE TITLE
Get rid of watchman

### ISSUE THREAD

**Issue by mikabytes** [tidenjs/tiden#24]
Having a dependency on Watchman requires the user to install two things. It's a hurdle, and it slows down adoption. We would be better off if we could find a suitable alternative that can be installed with NPM.

**Describe alternatives you've considered**
There is the popular https://github.com/paulmillr/chokidar project. However, I'm not sure if it is efficient across all platforms. It must use native bindings on Linux and Mac in order to be suitable. That is, `inotify` on Linux, and `fswatch` on Mac. Also there's Windows... Needs to be investigated.

**Comment by mikabytes** [comment]
Hey, @Seke1412 @AnatoliyZhurilo, would any of you be interested in taking a swing at this?

**Comment by Seke1412** [comment]
I think i can help on Mac with `fswatch`, meanwhile i have very little knowledge on Linux distro about `inotify`, and so far have no idea about native solution for Window @_@

**Comment by AnatoliyZhurilo** [comment]
Well, I can check it

**Comment by Seke1412** [comment]
Let me try on Mac. 
@mikabytes , i found that watchman come along with hotserve, i will start from `hotserve`, how do you feel?

**Comment by mikabytes** [comment]
Ah, yes, Tiden offloads its serving stuff onto [hotserve](mikabytes/hotserve) (one of my personal projects) which takes care of all those things. So this fix needs to be done there. True, true.

Hotserve is also open-source, so feel free to submit a PR there. Then @AnatoliyZhurilo and @Seke1412 can both take a stab at testing it on the various platforms!

**Comment by mikabytes** [comment]
This was fixed by mikabytes/hotserve#2
