### ISSUE TITLE
CLI allows names with dash

### ISSUE THREAD

**Issue by mikabytes** [tidenjs/tiden#40]
**Describe the bug**
Names for components, nanos, and streams should be camelCase. However, if snake-case is used, then it will happily perform the action anyway, leading to broken code.

**To Reproduce**
`tiden create component sidebar-tutorial`
`tiden create nano sidebar-tutorial`
`tiden create stream sidebar-tutorial`
`tiden create page sidebar-tutorial`

**Expected behavior**
It should fail with a clear error message

**Comment by Seke1412** [comment]
I intend to raise this bug yesterday, you're so fast man :)

**Comment by mikabytes** [comment]
Hahaha. Great minds think alike ;)

**Comment by mikabytes** [comment]
@Seke1412 Feel free to create new issues whenever you find things like this!
